{
 "title": "Evidently Dashboard",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Number of missing columns",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "share missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, share_missing_values\r\nFROM dummy_metrics "
    }
   ]
  },
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp,\r\n  prediction_drift\r\nFROM\r\n  dummy_metrics"
    }
   ]
  },
  {
   "title": "fare_amount quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, fare_amount_quantile FROM dummy_metrics"
    }
   ]
  }
 ]
}